projeto_fitas/Models/Etiqueta/Etiqueta.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC_Projeto.Models.Etiqueta
{
    public class Etiquetas
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto Increment (adiciona campo no banco = 1, 2,...)
        public int Id { get; set; }

        [StringLength(50)]
        [Required]
        public required string Nome { get; set; }

        [StringLength(150)]
        [Required]
        public required string Descricao { get; set; }

        [Required]
        public required byte[] Imagem { get; set; }
    }
}

projeto_fitas/Models/Etiqueta/EtiquetaViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace TCC_Projeto.Models.Etiqueta
{
    public class EtiquetaViewModel
    {
        [Required]
        public required string Nome { get; set; }

        [Required]
        public required string Descricao { get; set; }

        [Required]
        public required IFormFile Imagem { get; set; }
    }

    public class PDFViewModel
    {
        [Required(ErrorMessage = "O número do pedido é obrigatório")]
        public required string NPedido { get; set; }

        [Required(ErrorMessage = "A data é obrigatória")]
        public DateTime Data { get; set; }

        [Required(ErrorMessage = "O arquivo PDF é obrigatório")]
        public required IFormFile PDF { get; set; }
    }
}

projeto_fitas/Models/Etiqueta/FitaViewModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace TCC_Projeto.Models.Etiqueta
{   
    public class FitaViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public required int Id { get; set; }

        [Required]
        public required int impressao_id { get; set; }

        [Required]
        public required int quantidade { get; set; }

        [Required]
        public required int largura { get; set; }
    }
}

projeto_fitas/Models/Etiqueta/PDF.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC_Projeto.Models.Etiqueta
{
    public class PDF
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(50)]
        public required string? NPedido { get; set; }

        public DateTime? Data { get; set; }

        [StringLength(255)]
        public required string? CaminhoPDF { get; set; }
    }
}

projeto_fitas/Controllers/EtiquetaController.cs
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using TCC_Projeto.Models;
using TCC_Projeto.Models.Etiqueta;
using CsvHelper;
using System.Data.Entity;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.IO.Image;
using Microsoft.AspNetCore.Authorization;
using TCC_Projeto.Models.Usuario;


namespace TCC_Projeto.Controllers
{
    public class EtiquetaController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly Conexao _context;

        public EtiquetaController(IWebHostEnvironment hostingEnvironment, Conexao context)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }
        [Authorize]
        public IActionResult Etiqueta()
        {
            return View();
        }

        //Método para lidar com o envio do formulário via AJAX
        [HttpPost]
        public async Task<IActionResult> EnviarEtiqueta(EtiquetaViewModel etiqueta)
        {
            if (ModelState.IsValid)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await etiqueta.Imagem.CopyToAsync(memoryStream);
                    var etiquetaModel = new Etiquetas
                    {
                        Nome = etiqueta.Nome,
                        Descricao = etiqueta.Descricao,
                        Imagem = memoryStream.ToArray()
                    };

                    _context.Etiquetas.Add(etiquetaModel);
                    await _context.SaveChangesAsync();
                }

                return Json(new { success = true, message = "Dados enviados com sucesso!" });
            }

            return Json(new { success = false, message = "Erro ao enviar os dados." });
        }
       
        [HttpPost]
        public async Task<IActionResult> ExcluirEtiqueta(int id)
        {
            try
            {
                // Encontrar a etiqueta pelo ID
                var etiqueta = await _context.Etiquetas.FindAsync(id);

                // Verificar se a etiqueta foi encontrada
                if (etiqueta != null)
                {
                    // Remover a etiqueta do contexto
                    _context.Etiquetas.Remove(etiqueta);

                    // Salvar as alterações no banco de dados
                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Etiqueta excluída com sucesso!" });
                }
                else
                {
                    return Json(new { success = false, message = "Etiqueta não encontrada." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        public byte[]? ObterImagemDaEtiqueta(int id)
        {
            var etiqueta = _context.Etiquetas.FirstOrDefault(e => e.Id == id);

            if (etiqueta != null)
            {
                return etiqueta.Imagem;
            }

            return null;
        }

        [HttpGet]
        public IActionResult ObterTodasEtiquetas()
        {
            // Consultar todas as etiquetas do banco de dados
            var etiquetas = _context.Etiquetas.ToList();

            // Mapear os dados das etiquetas para um novo objeto com a imagem convertida para base64
            var etiquetasComImagemBase64 = etiquetas.Select(e => new
            {
                Id = e.Id,
                Nome = e.Nome,
                Descricao = e.Descricao,
                Imagem = Convert.ToBase64String(e.Imagem) // Convertendo a imagem para uma string base64
            }).ToList();

            return Json(etiquetasComImagemBase64);
        }

        [HttpGet]
        public IActionResult ModalFitas()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AdicionarNovaFita(FitaViewModel _request)
        {
            return Redirect("/Home/Entrar");
        }
    }
}

projeto_fitas/Views/Etiqueta/Etiqueta.cshtml
@model TCC_Projeto.Models.Etiqueta.EtiquetaViewModel

@{
    ViewBag.Title = "Formulário de Fita";
}

<div class="container">
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title text-dark">Adicionar nova Fita</h5>
            <br>
            <form id="etiquetaForm">
                @Html.AntiForgeryToken()
                <div class="row">
                    <div class="col-6">
                        @Html.LabelFor(model => model.Nome, new { @class = "text-dark" })
                        @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Nome)
                    </div>

                    <div class="form-group col-6">
                        @Html.LabelFor(model => model.Imagem, new { @class = "text-dark" })
                        <input type="file" name="Imagem" id="Imagem" class="form-control" />
                        @Html.ValidationMessageFor(model => model.Imagem)
                    </div>
                </div>
                <br>

                <div class="row">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Descricao, new { @class = "text-dark" })
                        @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Descricao)
                    </div>
                </div>
                <br>

                <button type="submit" class="btn btn-primary" id="btnSalvar">Salvar</button>
            </form>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <h5 class="card-title text-dark">Fitas</h5>
            <table class="table table-striped" id="etiquetasTable" width="100%">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th>Imagem</th>
                        <th>Excluir</th>
                    </tr>
                </thead>
                <tbody id="tabelaEtiquetasBody">
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmarExclusaoModal" tabindex="-1" aria-labelledby="confirmarExclusaoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmarExclusaoModalLabel">Confirmar Exclusão</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Tem certeza que deseja excluir esta fita?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger" id="confirmarExclusao">Sim</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // Inicializar DataTable
        carregarEtiquetas();

        $('#btnSalvar').click(function (event) {
            event.preventDefault(); // Evitar o comportamento padrão do formulário

            var formData = new FormData($('#etiquetaForm')[0]);

            $.ajax({
                url: '@Url.Action("EnviarEtiqueta", "Etiqueta")',
                type: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                success: function (response) {
                    // Remover a mensagem existente, se houver
                    carregarEtiquetas();
                    $('#mensagemSucesso').remove();
                    $('#etiquetaForm')[0].reset();


                    // Adicionar a mensagem de sucesso
                    var mensagem = '<div class="alert alert-success alert-dismissible fade show" style="position:absolute;width:100vw;" role="alert" id="mensagemSucesso">' +
                        'Fita adicionada com sucesso' +
                        '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>' +
                        '</div>';

                    // Adicionar a mensagem ao corpo do documento
                    $('body').append(mensagem);

                    // Remover a mensagem após 5 segundos
                    setTimeout(function () {
                        $('#mensagemSucesso').remove();
                    }, 3000);
                },
                error: function () {
                    alert('Erro ao enviar os dados.');
                }
            });
        });

        $('#tabelaEtiquetasBody').on('click', '.excluir-etiqueta', function () {
            var etiquetaId = $(this).data('id');

            // Abrir o modal de confirmação
            $('#confirmarExclusaoModal').modal('show');

            // Configurar a ação de exclusão no modal de confirmação
            $('#confirmarExclusao').click(function () {
                // Enviar solicitação AJAX para excluir a etiqueta
                $.ajax({
                    url: '@Url.Action("ExcluirEtiqueta", "Etiqueta")',
                    type: 'POST',
                    data: { id: etiquetaId },
                    success: function (response) {
                        if (response.success) {
                            $('#confirmarExclusaoModal').modal('hide');
                            $('#tabelaEtiquetasBody').empty();
                            location.reload()
                        }

                    },
                    error: function () {
                        alert('Erro ao excluir a etiqueta.');
                    }
                });
            });
           
        });

        function carregarEtiquetas() {
            $.ajax({
                url: '@Url.Action("ObterTodasEtiquetas", "Etiqueta")',
                type: 'GET',
                success: function (data) {
                    console.log(data);
                    // Limpar conteúdo existente na tabela
                    if ($.fn.DataTable.isDataTable('#etiquetasTable')) {
                        $('#etiquetasTable').DataTable().destroy();
                        $('#tabelaEtiquetasBody').empty();

                    }
                    // Preencher a tabela com os dados retornados
                    $.each(data, function (index, etiqueta) {
                        var imagemHTML = '<img src="data:image/jpeg;base64,' + etiqueta.imagem + '" width="100;" style="height: 20px;object-fit: cover;" />';
                        var linha = '<tr>' +
                            '<td style="width: 20%">' + etiqueta.nome + '</td>' +
                            '<td>' + etiqueta.descricao + '</td>' +
                            '<td style="width: 7%">' + imagemHTML + '</td>' +
                            '<td style="width: 3%; text-align: center;"><button data-id="' + etiqueta.id + '" class="btn btn-danger excluir-etiqueta"><i class="fa fa-trash"></i></button></td>'
                        '</tr>';
                        $('#tabelaEtiquetasBody').append(linha);
                    });

                    // Destruir DataTable existente, se houver


                    // Inicializar DataTable após preencher os dados
                    $('#etiquetasTable').DataTable({
                        language: {
                            url: '//cdn.datatables.net/plug-ins/1.10.24/i18n/Portuguese-Brasil.json'
                        }
                    });
                },
                error: function () {
                    alert('Erro ao carregar as etiquetas.');
                }
            });
        }
    });
</script>

projeto_fitas/Views/Etiqueta/ModalFitas.cshtml
@{
    Layout = null;

}
<form method="post" action="/Etiqueta/AdicionarNovaFita">
    <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Fitas</h5>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="fechar_modal">
            <span aria-hidden="true">&times;</span>
        </button>

    </div>
    <div class="modal-body">
        <div>
            <label class="form-label" for="id_fita">Fitas</label>
            <select name="fita" id="id_fita" class="form-control">
                <option value="" selected>------------</option>
            </select>
        </div>
        <br />

        <div class="row">
            <div class="col-6">
                <label class="form-label">Quantidade</label>
                <input type="number" name="quantidade" value="1" class="form-control" />
            </div>

            <div class="col-6">
                <label class="form-label">Largura</label>
                <input type="number" name="largura" value="1" class="form-control" />
            </div>
        </div>
    </div>
    <hr />

    <div id="container_imagem">Selecione uma fita para visualizar a imagem</div>
    <br>
    <div class="modal-footer d-flex justify-content-end">
        <button type="submit" class="btn btn-success">Adicionar</button>
    </div>
</form>
<script>
    let imagens = Array()
    $("#fechar_modal").click(() => {
        $("#modalMix").modal('hide')
    })

    $(document).ready(function () {
        $.ajax({
            url: '/etiqueta/obtertodasetiquetas',
            type: 'get',
            datatype: 'json',
            success: function (data) {
                data.map((item) => {
                    imagens.push({'id':item.id, "imagem":item.imagem})
                    $("#id_fita").append(
                        `<option value=${item.id}>${item.nome}</option>`
                    )
                })
            },
            error: function () {
                console.log('erro ao carregar as etiquetas.');
            }
        });

        console.log(imagens)
    })

    $("#id_fita").change(() => {
        var id_fita = $("#id_fita").val()
        carregarImagem(id_fita)
    })

    function carregarImagem(id) {
        imagens.map((item) => {
            $("#container_imagem").empty()
            $("#container_imagem").append()
            if (item.id == id) {
                $("#container_imagem").append(`<img src = "data:image/jpeg;base64,${item.imagem}" class="card-img-top" alt = "..." style = "height: 100px;object-fit: cover;" >`)
            }
        })

        if ($("#container_imagem").html() == '') {
            $("#container_imagem").append('Selecione uma fita para visualizar a imagem')
        }
    }
</script>